const colecaoElementos = [
  {
    "massaAtomica": "1.00794(4)",
    "numeroAtomico": "1",
    "raioAtomico": "37",
    "pontoDeEbulicao": "20",
    "tipoDeLigacao": "diatômica",
    "corHexCpk": "FFFFFF",
    "densidade": "8.99E-5",
    "afinidadeEletronica": "-73",
    "eletronegatividade": "2.2",
    "configuracaoEletronica": "1s1",
    "grupo": "não metal",
    "corGrupo": "#00FF00",
    "raioIonico": "",
    "energiaDeIonizacao": "1312",
    "pontoDeFusao": "14",
    "nome": "Hydrogen",
    "estadosDeOxidacao": "-1, 1",
    "estadoPadrao": "gasoso",
    "simbolo": "H",
    "raioDeVanDerWaals": "120",
    "anoDeDescoberta": "1766",
    "linha": 1,
    "coluna": 1
  },
  {
    "massaAtomica": "4.002602(2)",
    "numeroAtomico": "2",
    "raioAtomico": "32",
    "pontoDeEbulicao": "4",
    "tipoDeLigacao": "atômica",
    "corHexCpk": "D9FFFF",
    "densidade": "1.785E-4",
    "afinidadeEletronica": "0",
    "eletronegatividade": "",
    "configuracaoEletronica": "1s2",
    "grupo": "gás nobre",
    "corGrupo": "#FFEB3B",
    "raioIonico": "",
    "energiaDeIonizacao": "2372",
    "pontoDeFusao": "",
    "nome": "Helium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "gasoso",
    "simbolo": "He",
    "raioDeVanDerWaals": "140",
    "anoDeDescoberta": "1868",
    "linha": 1,
    "coluna": 18
  },
  {
    "massaAtomica": "6.941(2)",
    "numeroAtomico": "3",
    "raioAtomico": "134",
    "pontoDeEbulicao": "1615",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "CC80FF",
    "densidade": "0.535",
    "afinidadeEletronica": "-60",
    "eletronegatividade": "0.98",
    "configuracaoEletronica": "[He] 2s1",
    "grupo": "metal alcalino",
    "corGrupo": "#FF5733",
    "raioIonico": "76 (+1)",
    "energiaDeIonizacao": "520",
    "pontoDeFusao": "454",
    "nome": "Lithium",
    "estadosDeOxidacao": "1",
    "estadoPadrao": "sólido",
    "simbolo": "Li",
    "raioDeVanDerWaals": "182",
    "anoDeDescoberta": "1817",
    "linha": 2,
    "coluna": 1
  },
  {
    "massaAtomica": "9.012182(3)",
    "numeroAtomico": "4",
    "raioAtomico": "90",
    "pontoDeEbulicao": "2743",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "C2FF00",
    "densidade": "1.848",
    "afinidadeEletronica": "0",
    "eletronegatividade": "1.57",
    "configuracaoEletronica": "[He] 2s2",
    "grupo": "metal alcalino-terroso",
    "raioIonico": "45 (+2)",
    "energiaDeIonizacao": "900",
    "pontoDeFusao": "1560",
    "nome": "Beryllium",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "sólido",
    "simbolo": "Be",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1798",
    "linha": 2,
    "coluna": 2
  },
  {
    "massaAtomica": "10.811(7)",
    "numeroAtomico": "5",
    "raioAtomico": "82",
    "pontoDeEbulicao": "4273",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "FFB5B5",
    "densidade": "2.46",
    "afinidadeEletronica": "-27",
    "eletronegatividade": "2.04",
    "configuracaoEletronica": "[He] 2s2 2p1",
    "grupo": "metalóide",
    "raioIonico": "27 (+3)",
    "energiaDeIonizacao": "801",
    "pontoDeFusao": "2348",
    "nome": "Boron",
    "estadosDeOxidacao": "1, 2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "B",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1807",
    "linha": 2,
    "coluna": 13
  },
  {
    "massaAtomica": "12.0107(8)",
    "numeroAtomico": "6",
    "raioAtomico": "77",
    "pontoDeEbulicao": "4300",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "909090",
    "densidade": "2.26",
    "afinidadeEletronica": "-154",
    "eletronegatividade": "2.55",
    "configuracaoEletronica": "[He] 2s2 2p2",
    "grupo": "não metal",
    "raioIonico": "16 (+4)",
    "energiaDeIonizacao": "1087",
    "pontoDeFusao": "3823",
    "nome": "Carbon",
    "estadosDeOxidacao": "-4, -3, -2, -1, 1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "C",
    "raioDeVanDerWaals": "170",
    "anoDeDescoberta": "Ancient",
    "linha": 2,
    "coluna": 14
  },
  {
    "massaAtomica": "14.0067(2)",
    "numeroAtomico": "7",
    "raioAtomico": "75",
    "pontoDeEbulicao": "77",
    "tipoDeLigacao": "diatômica",
    "corHexCpk": "3050F8",
    "densidade": "0.001251",
    "afinidadeEletronica": "-7",
    "eletronegatividade": "3.04",
    "configuracaoEletronica": "[He] 2s2 2p3",
    "grupo": "não metal",
    "raioIonico": "146 (-3)",
    "energiaDeIonizacao": "1402",
    "pontoDeFusao": "63",
    "nome": "Nitrogen",
    "estadosDeOxidacao": "-3, -2, -1, 1, 2, 3, 4, 5",
    "estadoPadrao": "gasoso",
    "simbolo": "N",
    "raioDeVanDerWaals": "155",
    "anoDeDescoberta": "1772",
    "linha": 2,
    "coluna": 15
  },
  {
    "massaAtomica": "15.9994(3)",
    "numeroAtomico": "8",
    "raioAtomico": "73",
    "pontoDeEbulicao": "90",
    "tipoDeLigacao": "diatômica",
    "corHexCpk": "FF0D0D",
    "densidade": "0.001429",
    "afinidadeEletronica": "-141",
    "eletronegatividade": "3.44",
    "configuracaoEletronica": "[He] 2s2 2p4",
    "grupo": "não metal",
    "raioIonico": "140 (-2)",
    "energiaDeIonizacao": "1314",
    "pontoDeFusao": "55",
    "nome": "Oxygen",
    "estadosDeOxidacao": "-2, -1, 1, 2",
    "estadoPadrao": "gasoso",
    "simbolo": "O",
    "raioDeVanDerWaals": "152",
    "anoDeDescoberta": "1774",
    "linha": 2,
    "coluna": 16
  },
  {
    "massaAtomica": "18.9984032(5)",
    "numeroAtomico": "9",
    "raioAtomico": "71",
    "pontoDeEbulicao": "85",
    "tipoDeLigacao": "atômica",
    "corHexCpk": "9.0E51",
    "densidade": "0.001696",
    "afinidadeEletronica": "-328",
    "eletronegatividade": "3.98",
    "configuracaoEletronica": "[He] 2s2 2p5",
    "grupo": "halogênio",
    "raioIonico": "133 (-1)",
    "energiaDeIonizacao": "1681",
    "pontoDeFusao": "54",
    "nome": "Fluorine",
    "estadosDeOxidacao": "-1",
    "estadoPadrao": "gasoso",
    "simbolo": "F",
    "raioDeVanDerWaals": "147",
    "anoDeDescoberta": "1670",
    "linha": 2,
    "coluna": 17
  },
  {
    "massaAtomica": "20.1797(6)",
    "numeroAtomico": "10",
    "raioAtomico": "69",
    "pontoDeEbulicao": "27",
    "tipoDeLigacao": "atômica",
    "corHexCpk": "B3E3F5",
    "densidade": "9.0E-4",
    "afinidadeEletronica": "0",
    "eletronegatividade": "",
    "configuracaoEletronica": "[He] 2s2 2p6",
    "grupo": "gás nobre",
    "raioIonico": "",
    "energiaDeIonizacao": "2081",
    "pontoDeFusao": "25",
    "nome": "Neon",
    "estadosDeOxidacao": "",
    "estadoPadrao": "gasoso",
    "simbolo": "Ne",
    "raioDeVanDerWaals": "154",
    "anoDeDescoberta": "1898",
    "linha": 2,
    "coluna": 18
  },
  {
    "massaAtomica": "22.98976928(2)",
    "numeroAtomico": "11",
    "raioAtomico": "154",
    "pontoDeEbulicao": "1156",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "AB5CF2",
    "densidade": "0.968",
    "afinidadeEletronica": "-53",
    "eletronegatividade": "0.93",
    "configuracaoEletronica": "[Ne] 3s1",
    "grupo": "metal alcalino",
    "raioIonico": "102 (+1)",
    "energiaDeIonizacao": "496",
    "pontoDeFusao": "371",
    "nome": "Sodium",
    "estadosDeOxidacao": "-1, 1",
    "estadoPadrao": "sólido",
    "simbolo": "Na",
    "raioDeVanDerWaals": "227",
    "anoDeDescoberta": "1807",
    "linha": 3,
    "coluna": 1
  },
  {
    "massaAtomica": "24.3050(6)",
    "numeroAtomico": "12",
    "raioAtomico": "130",
    "pontoDeEbulicao": "1363",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "8AFF00",
    "densidade": "1.738",
    "afinidadeEletronica": "0",
    "eletronegatividade": "1.31",
    "configuracaoEletronica": "[Ne] 3s2",
    "grupo": "metal alcalino-terroso",
    "raioIonico": "72 (+2)",
    "energiaDeIonizacao": "738",
    "pontoDeFusao": "923",
    "nome": "Magnesium",
    "estadosDeOxidacao": "1, 2",
    "estadoPadrao": "sólido",
    "simbolo": "Mg",
    "raioDeVanDerWaals": "173",
    "anoDeDescoberta": "1808",
    "linha": 3,
    "coluna": 2
  },
  {
    "massaAtomica": "26.9815386(8)",
    "numeroAtomico": "13",
    "raioAtomico": "118",
    "pontoDeEbulicao": "2792",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "BFA6A6",
    "densidade": "2.7",
    "afinidadeEletronica": "-43",
    "eletronegatividade": "1.61",
    "configuracaoEletronica": "[Ne] 3s2 3p1",
    "grupo": "metal",
    "raioIonico": "53.5 (+3)",
    "energiaDeIonizacao": "578",
    "pontoDeFusao": "933",
    "nome": "Aluminum",
    "estadosDeOxidacao": "1, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Al",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "Ancient",
    "linha": 3,
    "coluna": 13
  },
  {
    "massaAtomica": "28.0855(3)",
    "numeroAtomico": "14",
    "raioAtomico": "111",
    "pontoDeEbulicao": "3173",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "F0C8A0",
    "densidade": "2.33",
    "afinidadeEletronica": "-134",
    "eletronegatividade": "1.9",
    "configuracaoEletronica": "[Ne] 3s2 3p2",
    "grupo": "metalóide",
    "raioIonico": "40 (+4)",
    "energiaDeIonizacao": "787",
    "pontoDeFusao": "1687",
    "nome": "Silicon",
    "estadosDeOxidacao": "-4, -3, -2, -1, 1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Si",
    "raioDeVanDerWaals": "210",
    "anoDeDescoberta": "1854",
    "linha": 3,
    "coluna": 14
  },
  {
    "massaAtomica": "30.973762(2)",
    "numeroAtomico": "15",
    "raioAtomico": "106",
    "pontoDeEbulicao": "554",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "FF8000",
    "densidade": "1.823",
    "afinidadeEletronica": "-72",
    "eletronegatividade": "2.19",
    "configuracaoEletronica": "[Ne] 3s2 3p3",
    "grupo": "não metal",
    "raioIonico": "44 (+3)",
    "energiaDeIonizacao": "1012",
    "pontoDeFusao": "317",
    "nome": "Phosphorus",
    "estadosDeOxidacao": "-3, -2, -1, 1, 2, 3, 4, 5",
    "estadoPadrao": "sólido",
    "simbolo": "P",
    "raioDeVanDerWaals": "180",
    "anoDeDescoberta": "1669",
    "linha": 3,
    "coluna": 15
  },
  {
    "massaAtomica": "32.065(5)",
    "numeroAtomico": "16",
    "raioAtomico": "102",
    "pontoDeEbulicao": "718",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "FFFF30",
    "densidade": "1.96",
    "afinidadeEletronica": "-200",
    "eletronegatividade": "2.58",
    "configuracaoEletronica": "[Ne] 3s2 3p4",
    "grupo": "não metal",
    "raioIonico": "184 (-2)",
    "energiaDeIonizacao": "1000",
    "pontoDeFusao": "388",
    "nome": "Sulfur",
    "estadosDeOxidacao": "-2, -1, 1, 2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "S",
    "raioDeVanDerWaals": "180",
    "anoDeDescoberta": "Ancient",
    "linha": 3,
    "coluna": 16
  },
  {
    "massaAtomica": "35.453(2)",
    "numeroAtomico": "17",
    "raioAtomico": "99",
    "pontoDeEbulicao": "239",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "1FF01F",
    "densidade": "0.003214",
    "afinidadeEletronica": "-349",
    "eletronegatividade": "3.16",
    "configuracaoEletronica": "[Ne] 3s2 3p5",
    "grupo": "halogênio",
    "raioIonico": "181 (-1)",
    "energiaDeIonizacao": "1251",
    "pontoDeFusao": "172",
    "nome": "Chlorine",
    "estadosDeOxidacao": "-1, 1, 2, 3, 4, 5, 6, 7",
    "estadoPadrao": "gasoso",
    "simbolo": "Cl",
    "raioDeVanDerWaals": "175",
    "anoDeDescoberta": "1774",
    "linha": 3,
    "coluna": 17
  },
  {
    "massaAtomica": "39.948(1)",
    "numeroAtomico": "18",
    "raioAtomico": "97",
    "pontoDeEbulicao": "87",
    "tipoDeLigacao": "atômica",
    "corHexCpk": "80D1E3",
    "densidade": "0.001784",
    "afinidadeEletronica": "0",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Ne] 3s2 3p6",
    "grupo": "gás nobre",
    "raioIonico": "",
    "energiaDeIonizacao": "1521",
    "pontoDeFusao": "84",
    "nome": "Argon",
    "estadosDeOxidacao": "",
    "estadoPadrao": "gasoso",
    "simbolo": "Ar",
    "raioDeVanDerWaals": "188",
    "anoDeDescoberta": "1894",
    "linha": 3,
    "coluna": 18
  },
  {
    "massaAtomica": "39.0983(1)",
    "numeroAtomico": "19",
    "raioAtomico": "196",
    "pontoDeEbulicao": "1032",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "8F40D4",
    "densidade": "0.856",
    "afinidadeEletronica": "-48",
    "eletronegatividade": "0.82",
    "configuracaoEletronica": "[Ar] 4s1",
    "grupo": "metal alcalino",
    "raioIonico": "138 (+1)",
    "energiaDeIonizacao": "419",
    "pontoDeFusao": "337",
    "nome": "Potassium",
    "estadosDeOxidacao": "1",
    "estadoPadrao": "sólido",
    "simbolo": "K",
    "raioDeVanDerWaals": "275",
    "anoDeDescoberta": "1807",
    "linha": 4,
    "coluna": 1
  },
  {
    "massaAtomica": "40.078(4)",
    "numeroAtomico": "20",
    "raioAtomico": "174",
    "pontoDeEbulicao": "1757",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "3DFF00",
    "densidade": "1.55",
    "afinidadeEletronica": "-2",
    "eletronegatividade": "1",
    "configuracaoEletronica": "[Ar] 4s2",
    "grupo": "metal alcalino-terroso",
    "raioIonico": "100 (+2)",
    "energiaDeIonizacao": "590",
    "pontoDeFusao": "1115",
    "nome": "Calcium",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "sólido",
    "simbolo": "Ca",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "Ancient",
    "linha": 4,
    "coluna": 2
  },
  {
    "massaAtomica": "44.955912(6)",
    "numeroAtomico": "21",
    "raioAtomico": "144",
    "pontoDeEbulicao": "3103",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "E6E6E6",
    "densidade": "2.985",
    "afinidadeEletronica": "-18",
    "eletronegatividade": "1.36",
    "configuracaoEletronica": "[Ar] 3d1 4s2",
    "grupo": "metal de transição",
    "raioIonico": "74.5 (+3)",
    "energiaDeIonizacao": "633",
    "pontoDeFusao": "1814",
    "nome": "Scandium",
    "estadosDeOxidacao": "1, 2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Sc",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1876",
    "linha": 4,
    "coluna": 3
  },
  {
    "massaAtomica": "47.867(1)",
    "numeroAtomico": "22",
    "raioAtomico": "136",
    "pontoDeEbulicao": "3560",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "BFC2C7",
    "densidade": "4.507",
    "afinidadeEletronica": "-8",
    "eletronegatividade": "1.54",
    "configuracaoEletronica": "[Ar] 3d2 4s2",
    "grupo": "metal de transição",
    "raioIonico": "86 (+2)",
    "energiaDeIonizacao": "659",
    "pontoDeFusao": "1941",
    "nome": "Titanium",
    "estadosDeOxidacao": "-1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Ti",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1791",
    "linha": 4,
    "coluna": 4
  },
  {
    "massaAtomica": "50.9415(1)",
    "numeroAtomico": "23",
    "raioAtomico": "125",
    "pontoDeEbulicao": "3680",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "A6A6AB",
    "densidade": "6.11",
    "afinidadeEletronica": "-51",
    "eletronegatividade": "1.63",
    "configuracaoEletronica": "[Ar] 3d3 4s2",
    "grupo": "metal de transição",
    "raioIonico": "79 (+2)",
    "energiaDeIonizacao": "651",
    "pontoDeFusao": "2183",
    "nome": "Vanadium",
    "estadosDeOxidacao": "-1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "V",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1803",
    "linha": 4,
    "coluna": 5
  },
  {
    "massaAtomica": "51.9961(6)",
    "numeroAtomico": "24",
    "raioAtomico": "127",
    "pontoDeEbulicao": "2944",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "8A99C7",
    "densidade": "7.14",
    "afinidadeEletronica": "-64",
    "eletronegatividade": "1.66",
    "configuracaoEletronica": "[Ar] 3d5 4s1",
    "grupo": "metal de transição",
    "raioIonico": "80 (+2*)",
    "energiaDeIonizacao": "653",
    "pontoDeFusao": "2180",
    "nome": "Chromium",
    "estadosDeOxidacao": "-2, -1, 1, 2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Cr",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "Ancient",
    "linha": 4,
    "coluna": 6
  },
  {
    "massaAtomica": "54.938045(5)",
    "numeroAtomico": "25",
    "raioAtomico": "139",
    "pontoDeEbulicao": "2334",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "9C7AC7",
    "densidade": "7.47",
    "afinidadeEletronica": "0",
    "eletronegatividade": "1.55",
    "configuracaoEletronica": "[Ar] 3d5 4s2",
    "grupo": "metal de transição",
    "raioIonico": "67 (+2)",
    "energiaDeIonizacao": "717",
    "pontoDeFusao": "1519",
    "nome": "Manganese",
    "estadosDeOxidacao": "-3, -2, -1, 1, 2, 3, 4, 5, 6, 7",
    "estadoPadrao": "sólido",
    "simbolo": "Mn",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1774",
    "linha": 4,
    "coluna": 7
  },
  {
    "massaAtomica": "55.845(2)",
    "numeroAtomico": "26",
    "raioAtomico": "125",
    "pontoDeEbulicao": "3134",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "E06633",
    "densidade": "7.874",
    "afinidadeEletronica": "-16",
    "eletronegatividade": "1.83",
    "configuracaoEletronica": "[Ar] 3d6 4s2",
    "grupo": "metal de transição",
    "raioIonico": "78 (+2*)",
    "energiaDeIonizacao": "763",
    "pontoDeFusao": "1811",
    "nome": "Iron",
    "estadosDeOxidacao": "-2, -1, 1, 2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Fe",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "Ancient",
    "linha": 4,
    "coluna": 8
  },
  {
    "massaAtomica": "58.933195(5)",
    "numeroAtomico": "27",
    "raioAtomico": "126",
    "pontoDeEbulicao": "3200",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "F090A0",
    "densidade": "8.9",
    "afinidadeEletronica": "-64",
    "eletronegatividade": "1.88",
    "configuracaoEletronica": "[Ar] 3d7 4s2",
    "grupo": "metal de transição",
    "raioIonico": "74.5 (+2*)",
    "energiaDeIonizacao": "760",
    "pontoDeFusao": "1768",
    "nome": "Cobalt",
    "estadosDeOxidacao": "-1, 1, 2, 3, 4, 5",
    "estadoPadrao": "sólido",
    "simbolo": "Co",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "Ancient",
    "linha": 4,
    "coluna": 9
  },
  {
    "massaAtomica": "58.6934(4)",
    "numeroAtomico": "28",
    "raioAtomico": "121",
    "pontoDeEbulicao": "3186",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "50D050",
    "densidade": "8.908",
    "afinidadeEletronica": "-112",
    "eletronegatividade": "1.91",
    "configuracaoEletronica": "[Ar] 3d8 4s2",
    "grupo": "metal de transição",
    "raioIonico": "69 (+2)",
    "energiaDeIonizacao": "737",
    "pontoDeFusao": "1728",
    "nome": "Nickel",
    "estadosDeOxidacao": "-1, 1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Ni",
    "raioDeVanDerWaals": "163",
    "anoDeDescoberta": "1751",
    "linha": 4,
    "coluna": 10
  },
  {
    "massaAtomica": "63.546(3)",
    "numeroAtomico": "29",
    "raioAtomico": "138",
    "pontoDeEbulicao": "3200",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "C88033",
    "densidade": "8.92",
    "afinidadeEletronica": "-118",
    "eletronegatividade": "1.9",
    "configuracaoEletronica": "[Ar] 3d10 4s1",
    "grupo": "metal de transição",
    "raioIonico": "77 (+1)",
    "energiaDeIonizacao": "746",
    "pontoDeFusao": "1358",
    "nome": "Copper",
    "estadosDeOxidacao": "1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Cu",
    "raioDeVanDerWaals": "140",
    "anoDeDescoberta": "Ancient",
    "linha": 4,
    "coluna": 11
  },
  {
    "massaAtomica": "65.38(2)",
    "numeroAtomico": "30",
    "raioAtomico": "131",
    "pontoDeEbulicao": "1180",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "7D80B0",
    "densidade": "7.14",
    "afinidadeEletronica": "0",
    "eletronegatividade": "1.65",
    "configuracaoEletronica": "[Ar] 3d10 4s2",
    "grupo": "metal de transição",
    "raioIonico": "74 (+2)",
    "energiaDeIonizacao": "906",
    "pontoDeFusao": "693",
    "nome": "Zinc",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "sólido",
    "simbolo": "Zn",
    "raioDeVanDerWaals": "139",
    "anoDeDescoberta": "1746",
    "linha": 4,
    "coluna": 12
  },
  {
    "massaAtomica": "69.723(1)",
    "numeroAtomico": "31",
    "raioAtomico": "126",
    "pontoDeEbulicao": "2477",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "C28F8F",
    "densidade": "5.904",
    "afinidadeEletronica": "-29",
    "eletronegatividade": "1.81",
    "configuracaoEletronica": "[Ar] 3d10 4s2 4p1",
    "grupo": "metal",
    "raioIonico": "62 (+3)",
    "energiaDeIonizacao": "579",
    "pontoDeFusao": "303",
    "nome": "Gallium",
    "estadosDeOxidacao": "1, 2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Ga",
    "raioDeVanDerWaals": "187",
    "anoDeDescoberta": "1875",
    "linha": 4,
    "coluna": 13
  },
  {
    "massaAtomica": "72.64(1)",
    "numeroAtomico": "32",
    "raioAtomico": "122",
    "pontoDeEbulicao": "3093",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "668F8F",
    "densidade": "5.323",
    "afinidadeEletronica": "-119",
    "eletronegatividade": "2.01",
    "configuracaoEletronica": "[Ar] 3d10 4s2 4p2",
    "grupo": "metalóide",
    "raioIonico": "73 (+2)",
    "energiaDeIonizacao": "762",
    "pontoDeFusao": "1211",
    "nome": "Germanium",
    "estadosDeOxidacao": "-4, 1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Ge",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1886",
    "linha": 4,
    "coluna": 14
  },
  {
    "massaAtomica": "74.92160(2)",
    "numeroAtomico": "33",
    "raioAtomico": "119",
    "pontoDeEbulicao": "887",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "BD80E3",
    "densidade": "5.727",
    "afinidadeEletronica": "-78",
    "eletronegatividade": "2.18",
    "configuracaoEletronica": "[Ar] 3d10 4s2 4p3",
    "grupo": "metalóide",
    "raioIonico": "58 (+3)",
    "energiaDeIonizacao": "947",
    "pontoDeFusao": "1090",
    "nome": "Arsenic",
    "estadosDeOxidacao": "-3, 2, 3, 5",
    "estadoPadrao": "sólido",
    "simbolo": "As",
    "raioDeVanDerWaals": "185",
    "anoDeDescoberta": "Ancient",
    "linha": 4,
    "coluna": 15
  },
  {
    "massaAtomica": "78.96(3)",
    "numeroAtomico": "34",
    "raioAtomico": "116",
    "pontoDeEbulicao": "958",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "FFA100",
    "densidade": "4.819",
    "afinidadeEletronica": "-195",
    "eletronegatividade": "2.55",
    "configuracaoEletronica": "[Ar] 3d10 4s2 4p4",
    "grupo": "não metal",
    "raioIonico": "198 (-2)",
    "energiaDeIonizacao": "941",
    "pontoDeFusao": "494",
    "nome": "Selenium",
    "estadosDeOxidacao": "-2, 2, 4, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Se",
    "raioDeVanDerWaals": "190",
    "anoDeDescoberta": "1817",
    "linha": 4,
    "coluna": 16
  },
  {
    "massaAtomica": "79.904(1)",
    "numeroAtomico": "35",
    "raioAtomico": "114",
    "pontoDeEbulicao": "332",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "A62929",
    "densidade": "3.12",
    "afinidadeEletronica": "-325",
    "eletronegatividade": "2.96",
    "configuracaoEletronica": "[Ar] 3d10 4s2 4p5",
    "grupo": "halogênio",
    "raioIonico": "196 (-1)",
    "energiaDeIonizacao": "1140",
    "pontoDeFusao": "266",
    "nome": "Bromine",
    "estadosDeOxidacao": "-1, 1, 3, 4, 5, 7",
    "estadoPadrao": "líquido",
    "simbolo": "Br",
    "raioDeVanDerWaals": "185",
    "anoDeDescoberta": "1826",
    "linha": 4,
    "coluna": 17
  },
  {
    "massaAtomica": "83.798(2)",
    "numeroAtomico": "36",
    "raioAtomico": "110",
    "pontoDeEbulicao": "120",
    "tipoDeLigacao": "atômica",
    "corHexCpk": "5CB8D1",
    "densidade": "0.00375",
    "afinidadeEletronica": "0",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Ar] 3d10 4s2 4p6",
    "grupo": "gás nobre",
    "raioIonico": "",
    "energiaDeIonizacao": "1351",
    "pontoDeFusao": "116",
    "nome": "Krypton",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "gasoso",
    "simbolo": "Kr",
    "raioDeVanDerWaals": "202",
    "anoDeDescoberta": "1898",
    "linha": 4,
    "coluna": 18
  },
  {
    "massaAtomica": "85.4678(3)",
    "numeroAtomico": "37",
    "raioAtomico": "211",
    "pontoDeEbulicao": "961",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "702EB0",
    "densidade": "1.532",
    "afinidadeEletronica": "-47",
    "eletronegatividade": "0.82",
    "configuracaoEletronica": "[Kr] 5s1",
    "grupo": "metal alcalino",
    "raioIonico": "152 (+1)",
    "energiaDeIonizacao": "403",
    "pontoDeFusao": "312",
    "nome": "Rubidium",
    "estadosDeOxidacao": "1",
    "estadoPadrao": "sólido",
    "simbolo": "Rb",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1861",
    "linha": 5,
    "coluna": 1
  },
  {
    "massaAtomica": "87.62(1)",
    "numeroAtomico": "38",
    "raioAtomico": "192",
    "pontoDeEbulicao": "1655",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00FF00",
    "densidade": "2.63",
    "afinidadeEletronica": "-5",
    "eletronegatividade": "0.95",
    "configuracaoEletronica": "[Kr] 5s2",
    "grupo": "metal alcalino-terroso",
    "raioIonico": "118 (+2)",
    "energiaDeIonizacao": "550",
    "pontoDeFusao": "1050",
    "nome": "Strontium",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "sólido",
    "simbolo": "Sr",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1790",
    "linha": 5,
    "coluna": 2
  },
  {
    "massaAtomica": "88.90585(2)",
    "numeroAtomico": "39",
    "raioAtomico": "162",
    "pontoDeEbulicao": "3618",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "94FFFF",
    "densidade": "4.472",
    "afinidadeEletronica": "-30",
    "eletronegatividade": "1.22",
    "configuracaoEletronica": "[Kr] 4d1 5s2",
    "grupo": "metal de transição",
    "raioIonico": "90 (+3)",
    "energiaDeIonizacao": "600",
    "pontoDeFusao": "1799",
    "nome": "Yttrium",
    "estadosDeOxidacao": "1, 2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Y",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1794",
    "linha": 5,
    "coluna": 3
  },
  {
    "massaAtomica": "91.224(2)",
    "numeroAtomico": "40",
    "raioAtomico": "148",
    "pontoDeEbulicao": "4682",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "94E0E0",
    "densidade": "6.511",
    "afinidadeEletronica": "-41",
    "eletronegatividade": "1.33",
    "configuracaoEletronica": "[Kr] 4d2 5s2",
    "grupo": "metal de transição",
    "raioIonico": "72 (+4)",
    "energiaDeIonizacao": "640",
    "pontoDeFusao": "2128",
    "nome": "Zirconium",
    "estadosDeOxidacao": "1, 2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Zr",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1789",
    "linha": 5,
    "coluna": 4
  },
  {
    "massaAtomica": "92.90638(2)",
    "numeroAtomico": "41",
    "raioAtomico": "137",
    "pontoDeEbulicao": "5017",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "73C2C9",
    "densidade": "8.57",
    "afinidadeEletronica": "-86",
    "eletronegatividade": "1.6",
    "configuracaoEletronica": "[Kr] 4d4 5s1",
    "grupo": "metal de transição",
    "raioIonico": "72 (+3)",
    "energiaDeIonizacao": "652",
    "pontoDeFusao": "2750",
    "nome": "Niobium",
    "estadosDeOxidacao": "-1, 2, 3, 4, 5",
    "estadoPadrao": "sólido",
    "simbolo": "Nb",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1801",
    "linha": 5,
    "coluna": 5
  },
  {
    "massaAtomica": "95.96(2)",
    "numeroAtomico": "42",
    "raioAtomico": "145",
    "pontoDeEbulicao": "4912",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "54B5B5",
    "densidade": "10.28",
    "afinidadeEletronica": "-72",
    "eletronegatividade": "2.16",
    "configuracaoEletronica": "[Kr] 4d5 5s1",
    "grupo": "metal de transição",
    "raioIonico": "69 (+3)",
    "energiaDeIonizacao": "684",
    "pontoDeFusao": "2896",
    "nome": "Molybdenum",
    "estadosDeOxidacao": "-2, -1, 1, 2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Mo",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1778",
    "linha": 5,
    "coluna": 6
  },
  {
    "massaAtomica": "98",
    "numeroAtomico": "43",
    "raioAtomico": "156",
    "pontoDeEbulicao": "4538",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "3B9E9E",
    "densidade": "11.5",
    "afinidadeEletronica": "-53",
    "eletronegatividade": "1.9",
    "configuracaoEletronica": "[Kr] 4d5 5s2",
    "grupo": "metal de transição",
    "raioIonico": "64.5 (+4)",
    "energiaDeIonizacao": "702",
    "pontoDeFusao": "2430",
    "nome": "Technetium",
    "estadosDeOxidacao": "-3, -1, 1, 2, 3, 4, 5, 6, 7",
    "estadoPadrao": "sólido",
    "simbolo": "Tc",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1937",
    "linha": 5,
    "coluna": 7
  },
  {
    "massaAtomica": "101.07(2)",
    "numeroAtomico": "44",
    "raioAtomico": "126",
    "pontoDeEbulicao": "4423",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "248F8F",
    "densidade": "12.37",
    "afinidadeEletronica": "-101",
    "eletronegatividade": "2.2",
    "configuracaoEletronica": "[Kr] 4d7 5s1",
    "grupo": "metal de transição",
    "raioIonico": "68 (+3)",
    "energiaDeIonizacao": "710",
    "pontoDeFusao": "2607",
    "nome": "Ruthenium",
    "estadosDeOxidacao": "-2, 1, 2, 3, 4, 5, 6, 7, 8",
    "estadoPadrao": "sólido",
    "simbolo": "Ru",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1827",
    "linha": 5,
    "coluna": 8
  },
  {
    "massaAtomica": "102.90550(2)",
    "numeroAtomico": "45",
    "raioAtomico": "135",
    "pontoDeEbulicao": "3968",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "0A7D8C",
    "densidade": "12.45",
    "afinidadeEletronica": "-110",
    "eletronegatividade": "2.28",
    "configuracaoEletronica": "[Kr] 4d8 5s1",
    "grupo": "metal de transição",
    "raioIonico": "66.5 (+3)",
    "energiaDeIonizacao": "720",
    "pontoDeFusao": "2237",
    "nome": "Rhodium",
    "estadosDeOxidacao": "-1, 1, 2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Rh",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1803",
    "linha": 5,
    "coluna": 9
  },
  {
    "massaAtomica": "106.42(1)",
    "numeroAtomico": "46",
    "raioAtomico": "131",
    "pontoDeEbulicao": "3236",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "6985",
    "densidade": "12.023",
    "afinidadeEletronica": "-54",
    "eletronegatividade": "2.2",
    "configuracaoEletronica": "[Kr] 4d10",
    "grupo": "metal de transição",
    "raioIonico": "59 (+1)",
    "energiaDeIonizacao": "804",
    "pontoDeFusao": "1828",
    "nome": "Palladium",
    "estadosDeOxidacao": "2, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Pd",
    "raioDeVanDerWaals": "163",
    "anoDeDescoberta": "1803",
    "linha": 5,
    "coluna": 10
  },
  {
    "massaAtomica": "107.8682(2)",
    "numeroAtomico": "47",
    "raioAtomico": "153",
    "pontoDeEbulicao": "2435",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "C0C0C0",
    "densidade": "10.49",
    "afinidadeEletronica": "-126",
    "eletronegatividade": "1.93",
    "configuracaoEletronica": "[Kr] 4d10 5s1",
    "grupo": "metal de transição",
    "raioIonico": "115 (+1)",
    "energiaDeIonizacao": "731",
    "pontoDeFusao": "1235",
    "nome": "Silver",
    "estadosDeOxidacao": "1, 2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Ag",
    "raioDeVanDerWaals": "172",
    "anoDeDescoberta": "Ancient",
    "linha": 5,
    "coluna": 11
  },
  {
    "massaAtomica": "112.411(8)",
    "numeroAtomico": "48",
    "raioAtomico": "148",
    "pontoDeEbulicao": "1040",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "FFD98F",
    "densidade": "8.65",
    "afinidadeEletronica": "0",
    "eletronegatividade": "1.69",
    "configuracaoEletronica": "[Kr] 4d10 5s2",
    "grupo": "metal de transição",
    "raioIonico": "95 (+2)",
    "energiaDeIonizacao": "868",
    "pontoDeFusao": "594",
    "nome": "Cadmium",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "sólido",
    "simbolo": "Cd",
    "raioDeVanDerWaals": "158",
    "anoDeDescoberta": "1817",
    "linha": 5,
    "coluna": 12
  },
  {
    "massaAtomica": "114.818(3)",
    "numeroAtomico": "49",
    "raioAtomico": "144",
    "pontoDeEbulicao": "2345",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "A67573",
    "densidade": "7.31",
    "afinidadeEletronica": "-29",
    "eletronegatividade": "1.78",
    "configuracaoEletronica": "[Kr] 4d10 5s2 5p1",
    "grupo": "metal",
    "raioIonico": "80 (+3)",
    "energiaDeIonizacao": "558",
    "pontoDeFusao": "430",
    "nome": "Indium",
    "estadosDeOxidacao": "1, 2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "In",
    "raioDeVanDerWaals": "193",
    "anoDeDescoberta": "1863",
    "linha": 5,
    "coluna": 13
  },
  {
    "massaAtomica": "118.710(7)",
    "numeroAtomico": "50",
    "raioAtomico": "141",
    "pontoDeEbulicao": "2875",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "668080",
    "densidade": "7.31",
    "afinidadeEletronica": "-107",
    "eletronegatividade": "1.96",
    "configuracaoEletronica": "[Kr] 4d10 5s2 5p2",
    "grupo": "metal",
    "raioIonico": "112 (+2)",
    "energiaDeIonizacao": "709",
    "pontoDeFusao": "505",
    "nome": "Tin",
    "estadosDeOxidacao": "-4, 2, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Sn",
    "raioDeVanDerWaals": "217",
    "anoDeDescoberta": "Ancient",
    "linha": 5,
    "coluna": 14
  },
  {
    "massaAtomica": "121.760(1)",
    "numeroAtomico": "51",
    "raioAtomico": "138",
    "pontoDeEbulicao": "1860",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "9E63B5",
    "densidade": "6.697",
    "afinidadeEletronica": "-103",
    "eletronegatividade": "2.05",
    "configuracaoEletronica": "[Kr] 4d10 5s2 5p3",
    "grupo": "metalóide",
    "raioIonico": "76 (+3)",
    "energiaDeIonizacao": "834",
    "pontoDeFusao": "904",
    "nome": "Antimony",
    "estadosDeOxidacao": "-3, 3, 5",
    "estadoPadrao": "sólido",
    "simbolo": "Sb",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "Ancient",
    "linha": 5,
    "coluna": 15
  },
  {
    "massaAtomica": "127.60(3)",
    "numeroAtomico": "52",
    "raioAtomico": "135",
    "pontoDeEbulicao": "1261",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "D47A00",
    "densidade": "6.24",
    "afinidadeEletronica": "-190",
    "eletronegatividade": "2.1",
    "configuracaoEletronica": "[Kr] 4d10 5s2 5p4",
    "grupo": "metalóide",
    "raioIonico": "221 (-2)",
    "energiaDeIonizacao": "869",
    "pontoDeFusao": "723",
    "nome": "Tellurium",
    "estadosDeOxidacao": "-2, 2, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Te",
    "raioDeVanDerWaals": "206",
    "anoDeDescoberta": "1782",
    "linha": 5,
    "coluna": 16
  },
  {
    "massaAtomica": "126.90447(3)",
    "numeroAtomico": "53",
    "raioAtomico": "133",
    "pontoDeEbulicao": "457",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "940094",
    "densidade": "4.94",
    "afinidadeEletronica": "-295",
    "eletronegatividade": "2.66",
    "configuracaoEletronica": "[Kr] 4d10 5s2 5p5",
    "grupo": "halogênio",
    "raioIonico": "220 (-1)",
    "energiaDeIonizacao": "1008",
    "pontoDeFusao": "387",
    "nome": "Iodine",
    "estadosDeOxidacao": "-1, 1, 3, 5, 7",
    "estadoPadrao": "sólido",
    "simbolo": "I",
    "raioDeVanDerWaals": "198",
    "anoDeDescoberta": "1811",
    "linha": 5,
    "coluna": 17
  },
  {
    "massaAtomica": "131.293(6)",
    "numeroAtomico": "54",
    "raioAtomico": "130",
    "pontoDeEbulicao": "165",
    "tipoDeLigacao": "atômica",
    "corHexCpk": "429EB0",
    "densidade": "0.0059",
    "afinidadeEletronica": "0",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Kr] 4d10 5s2 5p6",
    "grupo": "gás nobre",
    "raioIonico": "48 (+8)",
    "energiaDeIonizacao": "1170",
    "pontoDeFusao": "161",
    "nome": "Xenon",
    "estadosDeOxidacao": "2, 4, 6, 8",
    "estadoPadrao": "gasoso",
    "simbolo": "Xe",
    "raioDeVanDerWaals": "216",
    "anoDeDescoberta": "1898",
    "linha": 5,
    "coluna": 18
  },
  {
    "massaAtomica": "132.9054519(2)",
    "numeroAtomico": "55",
    "raioAtomico": "225",
    "pontoDeEbulicao": "944",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "57178F",
    "densidade": "1.879",
    "afinidadeEletronica": "-46",
    "eletronegatividade": "0.79",
    "configuracaoEletronica": "[Xe] 6s1",
    "grupo": "metal alcalino",
    "raioIonico": "167 (+1)",
    "energiaDeIonizacao": "376",
    "pontoDeFusao": "302",
    "nome": "Cesium",
    "estadosDeOxidacao": "1",
    "estadoPadrao": "sólido",
    "simbolo": "Cs",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1860",
    "linha": 6,
    "coluna": 1
  },
  {
    "massaAtomica": "137.327(7)",
    "numeroAtomico": "56",
    "raioAtomico": "198",
    "pontoDeEbulicao": "2143",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00C900",
    "densidade": "3.51",
    "afinidadeEletronica": "-14",
    "eletronegatividade": "0.89",
    "configuracaoEletronica": "[Xe] 6s2",
    "grupo": "metal alcalino-terroso",
    "raioIonico": "135 (+2)",
    "energiaDeIonizacao": "503",
    "pontoDeFusao": "1000",
    "nome": "Barium",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "sólido",
    "simbolo": "Ba",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1808",
    "linha": 6,
    "coluna": 2
  },
  {
    "massaAtomica": "138.90547(7)",
    "numeroAtomico": "57",
    "raioAtomico": "169",
    "pontoDeEbulicao": "3737",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "70D4FF",
    "densidade": "6.146",
    "afinidadeEletronica": "-48",
    "eletronegatividade": "1.1",
    "configuracaoEletronica": "[Xe] 5d1 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "103.2 (+3)",
    "energiaDeIonizacao": "538",
    "pontoDeFusao": "1193",
    "nome": "Lanthanum",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "La",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1839",
    "linha": 9,
    "coluna": 4
  },
  {
    "massaAtomica": "140.116(1)",
    "numeroAtomico": "58",
    "raioAtomico": "",
    "pontoDeEbulicao": "3633",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "FFFFC7",
    "densidade": "6.689",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.12",
    "configuracaoEletronica": "[Xe] 4f1 5d1 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "102 (+3)",
    "energiaDeIonizacao": "534",
    "pontoDeFusao": "1071",
    "nome": "Cerium",
    "estadosDeOxidacao": "2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Ce",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1803",
    "linha": 9,
    "coluna": 5
  },
  {
    "massaAtomica": "140.90765(2)",
    "numeroAtomico": "59",
    "raioAtomico": "",
    "pontoDeEbulicao": "3563",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "D9FFC7",
    "densidade": "6.64",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.13",
    "configuracaoEletronica": "[Xe] 4f3 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "99 (+3)",
    "energiaDeIonizacao": "527",
    "pontoDeFusao": "1204",
    "nome": "Praseodymium",
    "estadosDeOxidacao": "2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Pr",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1885",
    "linha": 9,
    "coluna": 6
  },
  {
    "massaAtomica": "144.242(3)",
    "numeroAtomico": "60",
    "raioAtomico": "",
    "pontoDeEbulicao": "3373",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "C7FFC7",
    "densidade": "7.01",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.14",
    "configuracaoEletronica": "[Xe] 4f4 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "129 (+2)",
    "energiaDeIonizacao": "533",
    "pontoDeFusao": "1294",
    "nome": "Neodymium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Nd",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1885",
    "linha": 9,
    "coluna": 7
  },
  {
    "massaAtomica": "145",
    "numeroAtomico": "61",
    "raioAtomico": "",
    "pontoDeEbulicao": "3273",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "A3FFC7",
    "densidade": "7.264",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.13",
    "configuracaoEletronica": "[Xe] 4f5 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "97 (+3)",
    "energiaDeIonizacao": "540",
    "pontoDeFusao": "1373",
    "nome": "Promethium",
    "estadosDeOxidacao": "3",
    "estadoPadrao": "sólido",
    "simbolo": "Pm",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1947",
    "linha": 9,
    "coluna": 8
  },
  {
    "massaAtomica": "150.36(2)",
    "numeroAtomico": "62",
    "raioAtomico": "",
    "pontoDeEbulicao": "2076",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "8FFFC7",
    "densidade": "7.353",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.17",
    "configuracaoEletronica": "[Xe] 4f6 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "122 (+2)",
    "energiaDeIonizacao": "545",
    "pontoDeFusao": "1345",
    "nome": "Samarium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Sm",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1853",
    "linha": 9,
    "coluna": 9
  },
  {
    "massaAtomica": "151.964(1)",
    "numeroAtomico": "63",
    "raioAtomico": "",
    "pontoDeEbulicao": "1800",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "61FFC7",
    "densidade": "5.244",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.2",
    "configuracaoEletronica": "[Xe] 4f7 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "117 (+2)",
    "energiaDeIonizacao": "547",
    "pontoDeFusao": "1095",
    "nome": "Europium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Eu",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1901",
    "linha": 9,
    "coluna": 10
  },
  {
    "massaAtomica": "157.25(3)",
    "numeroAtomico": "64",
    "raioAtomico": "",
    "pontoDeEbulicao": "3523",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "45FFC7",
    "densidade": "7.901",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.2",
    "configuracaoEletronica": "[Xe] 4f7 5d1 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "93.8 (+3)",
    "energiaDeIonizacao": "593",
    "pontoDeFusao": "1586",
    "nome": "Gadolinium",
    "estadosDeOxidacao": "1, 2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Gd",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1880",
    "linha": 9,
    "coluna": 11
  },
  {
    "massaAtomica": "158.92535(2)",
    "numeroAtomico": "65",
    "raioAtomico": "",
    "pontoDeEbulicao": "3503",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "30FFC7",
    "densidade": "8.219",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.2",
    "configuracaoEletronica": "[Xe] 4f9 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "92.3 (+3)",
    "energiaDeIonizacao": "566",
    "pontoDeFusao": "1629",
    "nome": "Terbium",
    "estadosDeOxidacao": "1, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Tb",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1843",
    "linha": 9,
    "coluna": 12
  },
  {
    "massaAtomica": "162.500(1)",
    "numeroAtomico": "66",
    "raioAtomico": "",
    "pontoDeEbulicao": "2840",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "1FFFC7",
    "densidade": "8.551",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.22",
    "configuracaoEletronica": "[Xe] 4f10 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "107 (+2)",
    "energiaDeIonizacao": "573",
    "pontoDeFusao": "1685",
    "nome": "Dysprosium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Dy",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1886",
    "linha": 9,
    "coluna": 13
  },
  {
    "massaAtomica": "164.93032(2)",
    "numeroAtomico": "67",
    "raioAtomico": "",
    "pontoDeEbulicao": "2973",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00FF9C",
    "densidade": "8.795",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.23",
    "configuracaoEletronica": "[Xe] 4f11 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "90.1 (+3)",
    "energiaDeIonizacao": "581",
    "pontoDeFusao": "1747",
    "nome": "Holmium",
    "estadosDeOxidacao": "3",
    "estadoPadrao": "sólido",
    "simbolo": "Ho",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1878",
    "linha": 9,
    "coluna": 14
  },
  {
    "massaAtomica": "167.259(3)",
    "numeroAtomico": "68",
    "raioAtomico": "",
    "pontoDeEbulicao": "3141",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "0",
    "densidade": "9.066",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.24",
    "configuracaoEletronica": "[Xe] 4f12 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "89 (+3)",
    "energiaDeIonizacao": "589",
    "pontoDeFusao": "1770",
    "nome": "Erbium",
    "estadosDeOxidacao": "3",
    "estadoPadrao": "sólido",
    "simbolo": "Er",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1842",
    "linha": 9,
    "coluna": 15
  },
  {
    "massaAtomica": "168.93421(2)",
    "numeroAtomico": "69",
    "raioAtomico": "",
    "pontoDeEbulicao": "2223",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00D452",
    "densidade": "9.321",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.25",
    "configuracaoEletronica": "[Xe] 4f13 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "103 (+2)",
    "energiaDeIonizacao": "597",
    "pontoDeFusao": "1818",
    "nome": "Thulium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Tm",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1879",
    "linha": 9,
    "coluna": 16
  },
  {
    "massaAtomica": "173.054(5)",
    "numeroAtomico": "70",
    "raioAtomico": "",
    "pontoDeEbulicao": "1469",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00BF38",
    "densidade": "6.57",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.1",
    "configuracaoEletronica": "[Xe] 4f14 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "102 (+2)",
    "energiaDeIonizacao": "603",
    "pontoDeFusao": "1092",
    "nome": "Ytterbium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Yb",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1878",
    "linha": 9,
    "coluna": 17
  },
  {
    "massaAtomica": "174.9668(1)",
    "numeroAtomico": "71",
    "raioAtomico": "160",
    "pontoDeEbulicao": "3675",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00AB24",
    "densidade": "9.841",
    "afinidadeEletronica": "-50",
    "eletronegatividade": "1.27",
    "configuracaoEletronica": "[Xe] 4f14 5d1 6s2",
    "grupo": "lantanídeo",
    "raioIonico": "86.1 (+3)",
    "energiaDeIonizacao": "524",
    "pontoDeFusao": "1936",
    "nome": "Lutetium",
    "estadosDeOxidacao": "3",
    "estadoPadrao": "sólido",
    "simbolo": "Lu",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1907",
    "linha": 9,
    "coluna": 18
  },
  {
    "massaAtomica": "178.49(2)",
    "numeroAtomico": "72",
    "raioAtomico": "150",
    "pontoDeEbulicao": "4876",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "4DC2FF",
    "densidade": "13.31",
    "afinidadeEletronica": "0",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Xe] 4f14 5d2 6s2",
    "grupo": "metal de transição",
    "raioIonico": "71 (+4)",
    "energiaDeIonizacao": "659",
    "pontoDeFusao": "2506",
    "nome": "Hafnium",
    "estadosDeOxidacao": "2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Hf",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1923",
    "linha": 6,
    "coluna": 4
  },
  {
    "massaAtomica": "180.94788(2)",
    "numeroAtomico": "73",
    "raioAtomico": "138",
    "pontoDeEbulicao": "5731",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "4DA6FF",
    "densidade": "16.65",
    "afinidadeEletronica": "-31",
    "eletronegatividade": "1.5",
    "configuracaoEletronica": "[Xe] 4f14 5d3 6s2",
    "grupo": "metal de transição",
    "raioIonico": "72 (+3)",
    "energiaDeIonizacao": "761",
    "pontoDeFusao": "3290",
    "nome": "Tantalum",
    "estadosDeOxidacao": "-1, 2, 3, 4, 5",
    "estadoPadrao": "sólido",
    "simbolo": "Ta",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1802",
    "linha": 6,
    "coluna": 5
  },
  {
    "massaAtomica": "183.84(1)",
    "numeroAtomico": "74",
    "raioAtomico": "146",
    "pontoDeEbulicao": "5828",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "2194D6",
    "densidade": "19.25",
    "afinidadeEletronica": "-79",
    "eletronegatividade": "2.36",
    "configuracaoEletronica": "[Xe] 4f14 5d4 6s2",
    "grupo": "metal de transição",
    "raioIonico": "66 (+4)",
    "energiaDeIonizacao": "770",
    "pontoDeFusao": "3695",
    "nome": "Tungsten",
    "estadosDeOxidacao": "-2, -1, 1, 2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "W",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1783",
    "linha": 6,
    "coluna": 6
  },
  {
    "massaAtomica": "186.207(1)",
    "numeroAtomico": "75",
    "raioAtomico": "159",
    "pontoDeEbulicao": "5869",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "267DAB",
    "densidade": "21.02",
    "afinidadeEletronica": "-15",
    "eletronegatividade": "1.9",
    "configuracaoEletronica": "[Xe] 4f14 5d5 6s2",
    "grupo": "metal de transição",
    "raioIonico": "63 (+4)",
    "energiaDeIonizacao": "760",
    "pontoDeFusao": "3459",
    "nome": "Rhenium",
    "estadosDeOxidacao": "-3, -1, 1, 2, 3, 4, 5, 6, 7",
    "estadoPadrao": "sólido",
    "simbolo": "Re",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1925",
    "linha": 6,
    "coluna": 7
  },
  {
    "massaAtomica": "190.23(3)",
    "numeroAtomico": "76",
    "raioAtomico": "128",
    "pontoDeEbulicao": "5285",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "266696",
    "densidade": "22.61",
    "afinidadeEletronica": "-106",
    "eletronegatividade": "2.2",
    "configuracaoEletronica": "[Xe] 4f14 5d6 6s2",
    "grupo": "metal de transição",
    "raioIonico": "63 (+4)",
    "energiaDeIonizacao": "840",
    "pontoDeFusao": "3306",
    "nome": "Osmium",
    "estadosDeOxidacao": "-2, -1, 1, 2, 3, 4, 5, 6, 7, 8",
    "estadoPadrao": "sólido",
    "simbolo": "Os",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1803",
    "linha": 6,
    "coluna": 8
  },
  {
    "massaAtomica": "192.217(3)",
    "numeroAtomico": "77",
    "raioAtomico": "137",
    "pontoDeEbulicao": "4701",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "175487",
    "densidade": "22.65",
    "afinidadeEletronica": "-151",
    "eletronegatividade": "2.2",
    "configuracaoEletronica": "[Xe] 4f14 5d7 6s2",
    "grupo": "metal de transição",
    "raioIonico": "68 (+3)",
    "energiaDeIonizacao": "880",
    "pontoDeFusao": "2739",
    "nome": "Iridium",
    "estadosDeOxidacao": "-3, -1, 1, 2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Ir",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1803",
    "linha": 6,
    "coluna": 9
  },
  {
    "massaAtomica": "195.084(9)",
    "numeroAtomico": "78",
    "raioAtomico": "128",
    "pontoDeEbulicao": "4098",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "D0D0E0",
    "densidade": "21.09",
    "afinidadeEletronica": "-205",
    "eletronegatividade": "2.28",
    "configuracaoEletronica": "[Xe] 4f14 5d9 6s1",
    "grupo": "metal de transição",
    "raioIonico": "86 (+2)",
    "energiaDeIonizacao": "870",
    "pontoDeFusao": "2041",
    "nome": "Platinum",
    "estadosDeOxidacao": "2, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Pt",
    "raioDeVanDerWaals": "175",
    "anoDeDescoberta": "Ancient",
    "linha": 6,
    "coluna": 10
  },
  {
    "massaAtomica": "196.966569(4)",
    "numeroAtomico": "79",
    "raioAtomico": "144",
    "pontoDeEbulicao": "3129",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "FFD123",
    "densidade": "19.3",
    "afinidadeEletronica": "-223",
    "eletronegatividade": "2.54",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s1",
    "grupo": "metal de transição",
    "raioIonico": "137 (+1)",
    "energiaDeIonizacao": "890",
    "pontoDeFusao": "1337",
    "nome": "Gold",
    "estadosDeOxidacao": "-1, 1, 2, 3, 5",
    "estadoPadrao": "sólido",
    "simbolo": "Au",
    "raioDeVanDerWaals": "166",
    "anoDeDescoberta": "Ancient",
    "linha": 6,
    "coluna": 11
  },
  {
    "massaAtomica": "200.59(2)",
    "numeroAtomico": "80",
    "raioAtomico": "149",
    "pontoDeEbulicao": "630",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "B8B8D0",
    "densidade": "13.534",
    "afinidadeEletronica": "0",
    "eletronegatividade": "2",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s2",
    "grupo": "metal de transição",
    "raioIonico": "119 (+1)",
    "energiaDeIonizacao": "1007",
    "pontoDeFusao": "234",
    "nome": "Mercury",
    "estadosDeOxidacao": "1, 2, 4",
    "estadoPadrao": "líquido",
    "simbolo": "Hg",
    "raioDeVanDerWaals": "155",
    "anoDeDescoberta": "Ancient",
    "linha": 6,
    "coluna": 12
  },
  {
    "massaAtomica": "204.3833(2)",
    "numeroAtomico": "81",
    "raioAtomico": "148",
    "pontoDeEbulicao": "1746",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "A6544D",
    "densidade": "11.85",
    "afinidadeEletronica": "-19",
    "eletronegatividade": "2.04",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s2 6p1",
    "grupo": "metal",
    "raioIonico": "150 (+1)",
    "energiaDeIonizacao": "589",
    "pontoDeFusao": "577",
    "nome": "Thallium",
    "estadosDeOxidacao": "1, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Tl",
    "raioDeVanDerWaals": "196",
    "anoDeDescoberta": "1861",
    "linha": 6,
    "coluna": 13
  },
  {
    "massaAtomica": "207.2(1)",
    "numeroAtomico": "82",
    "raioAtomico": "147",
    "pontoDeEbulicao": "2022",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "575961",
    "densidade": "11.34",
    "afinidadeEletronica": "-35",
    "eletronegatividade": "2.33",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s2 6p2",
    "grupo": "metal",
    "raioIonico": "119 (+2)",
    "energiaDeIonizacao": "716",
    "pontoDeFusao": "601",
    "nome": "Lead",
    "estadosDeOxidacao": "-4, 2, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Pb",
    "raioDeVanDerWaals": "202",
    "anoDeDescoberta": "Ancient",
    "linha": 6,
    "coluna": 14
  },
  {
    "massaAtomica": "208.98040(1)",
    "numeroAtomico": "83",
    "raioAtomico": "146",
    "pontoDeEbulicao": "1837",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "9E4FB5",
    "densidade": "9.78",
    "afinidadeEletronica": "-91",
    "eletronegatividade": "2.02",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s2 6p3",
    "grupo": "metal",
    "raioIonico": "103 (+3)",
    "energiaDeIonizacao": "703",
    "pontoDeFusao": "544",
    "nome": "Bismuth",
    "estadosDeOxidacao": "-3, 3, 5",
    "estadoPadrao": "sólido",
    "simbolo": "Bi",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "Ancient",
    "linha": 6,
    "coluna": 15
  },
  {
    "massaAtomica": "209",
    "numeroAtomico": "84",
    "raioAtomico": "",
    "pontoDeEbulicao": "1235",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "AB5C00",
    "densidade": "9.196",
    "afinidadeEletronica": "-183",
    "eletronegatividade": "2",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s2 6p4",
    "grupo": "metalóide",
    "raioIonico": "94 (+4)",
    "energiaDeIonizacao": "812",
    "pontoDeFusao": "527",
    "nome": "Polonium",
    "estadosDeOxidacao": "-2, 2, 4, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Po",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1898",
    "linha": 6,
    "coluna": 16
  },
  {
    "massaAtomica": "210",
    "numeroAtomico": "85",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "rede covalente",
    "corHexCpk": "754F45",
    "densidade": "",
    "afinidadeEletronica": "-270",
    "eletronegatividade": "2.2",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s2 6p5",
    "grupo": "halogênio",
    "raioIonico": "62 (+7)",
    "energiaDeIonizacao": "920",
    "pontoDeFusao": "575",
    "nome": "Astatine",
    "estadosDeOxidacao": "-1, 1, 3, 5",
    "estadoPadrao": "sólido",
    "simbolo": "At",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1940",
    "linha": 6,
    "coluna": 17
  },
  {
    "massaAtomica": "222",
    "numeroAtomico": "86",
    "raioAtomico": "145",
    "pontoDeEbulicao": "211",
    "tipoDeLigacao": "atômica",
    "corHexCpk": "428296",
    "densidade": "0.00973",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Xe] 4f14 5d10 6s2 6p6",
    "grupo": "gás nobre",
    "raioIonico": "",
    "energiaDeIonizacao": "1037",
    "pontoDeFusao": "202",
    "nome": "Radon",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "gasoso",
    "simbolo": "Rn",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1900",
    "linha": 6,
    "coluna": 18
  },
  {
    "massaAtomica": "223",
    "numeroAtomico": "87",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "420066",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "0.7",
    "configuracaoEletronica": "[Rn] 7s1",
    "grupo": "metal alcalino",
    "raioIonico": "180 (+1)",
    "energiaDeIonizacao": "380",
    "pontoDeFusao": "",
    "nome": "Francium",
    "estadosDeOxidacao": "1",
    "estadoPadrao": "sólido",
    "simbolo": "Fr",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1939",
    "linha": 7,
    "coluna": 1
  },
  {
    "massaAtomica": "226",
    "numeroAtomico": "88",
    "raioAtomico": "",
    "pontoDeEbulicao": "2010",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "007D00",
    "densidade": "5",
    "afinidadeEletronica": "",
    "eletronegatividade": "0.9",
    "configuracaoEletronica": "[Rn] 7s2",
    "grupo": "metal alcalino-terroso",
    "raioIonico": "148 (+2)",
    "energiaDeIonizacao": "509",
    "pontoDeFusao": "973",
    "nome": "Radium",
    "estadosDeOxidacao": "2",
    "estadoPadrao": "sólido",
    "simbolo": "Ra",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1898",
    "linha": 7,
    "coluna": 2
  },
  {
    "massaAtomica": "227",
    "numeroAtomico": "89",
    "raioAtomico": "",
    "pontoDeEbulicao": "3473",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "70ABFA",
    "densidade": "10.07",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.1",
    "configuracaoEletronica": "[Rn] 6d1 7s2",
    "grupo": "actinoid",
    "raioIonico": "112 (+3)",
    "energiaDeIonizacao": "499",
    "pontoDeFusao": "1323",
    "nome": "Actinium",
    "estadosDeOxidacao": "3",
    "estadoPadrao": "sólido",
    "simbolo": "Ac",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1899",
    "linha": 10,
    "coluna": 4
  },
  {
    "massaAtomica": "232.03806(2)",
    "numeroAtomico": "90",
    "raioAtomico": "",
    "pontoDeEbulicao": "5093",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00BAFF",
    "densidade": "11.724",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 6d2 7s2",
    "grupo": "actinoid",
    "raioIonico": "94 (+4)",
    "energiaDeIonizacao": "587",
    "pontoDeFusao": "2023",
    "nome": "Thorium",
    "estadosDeOxidacao": "2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Th",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1828",
    "linha": 10,
    "coluna": 5
  },
  {
    "massaAtomica": "231.03588(2)",
    "numeroAtomico": "91",
    "raioAtomico": "",
    "pontoDeEbulicao": "4273",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "00A1FF",
    "densidade": "15.37",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.5",
    "configuracaoEletronica": "[Rn] 5f2 6d1 7s2",
    "grupo": "actinoid",
    "raioIonico": "104 (+3)",
    "energiaDeIonizacao": "568",
    "pontoDeFusao": "1845",
    "nome": "Protactinium",
    "estadosDeOxidacao": "3, 4, 5",
    "estadoPadrao": "sólido",
    "simbolo": "Pa",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1913",
    "linha": 10,
    "coluna": 6
  },
  {
    "massaAtomica": "238.02891(3)",
    "numeroAtomico": "92",
    "raioAtomico": "",
    "pontoDeEbulicao": "4200",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "008FFF",
    "densidade": "19.05",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.38",
    "configuracaoEletronica": "[Rn] 5f3 6d1 7s2",
    "grupo": "actinoid",
    "raioIonico": "102.5 (+3)",
    "energiaDeIonizacao": "598",
    "pontoDeFusao": "1408",
    "nome": "Uranium",
    "estadosDeOxidacao": "3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "U",
    "raioDeVanDerWaals": "186",
    "anoDeDescoberta": "1789",
    "linha": 10,
    "coluna": 7
  },
  {
    "massaAtomica": "237",
    "numeroAtomico": "93",
    "raioAtomico": "",
    "pontoDeEbulicao": "4273",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "0080FF",
    "densidade": "20.45",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.36",
    "configuracaoEletronica": "[Rn] 5f4 6d1 7s2",
    "grupo": "actinoid",
    "raioIonico": "110 (+2)",
    "energiaDeIonizacao": "605",
    "pontoDeFusao": "917",
    "nome": "Neptunium",
    "estadosDeOxidacao": "3, 4, 5, 6, 7",
    "estadoPadrao": "sólido",
    "simbolo": "Np",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1940",
    "linha": 10,
    "coluna": 8
  },
  {
    "massaAtomica": "244",
    "numeroAtomico": "94",
    "raioAtomico": "",
    "pontoDeEbulicao": "3503",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "006BFF",
    "densidade": "19.816",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.28",
    "configuracaoEletronica": "[Rn] 5f6 7s2",
    "grupo": "actinoid",
    "raioIonico": "100 (+3)",
    "energiaDeIonizacao": "585",
    "pontoDeFusao": "913",
    "nome": "Plutonium",
    "estadosDeOxidacao": "3, 4, 5, 6, 7",
    "estadoPadrao": "sólido",
    "simbolo": "Pu",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1940",
    "linha": 10,
    "coluna": 9
  },
  {
    "massaAtomica": "243",
    "numeroAtomico": "95",
    "raioAtomico": "",
    "pontoDeEbulicao": "2284",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "545CF2",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f7 7s2",
    "grupo": "actinoid",
    "raioIonico": "126 (+2)",
    "energiaDeIonizacao": "578",
    "pontoDeFusao": "1449",
    "nome": "Americium",
    "estadosDeOxidacao": "2, 3, 4, 5, 6",
    "estadoPadrao": "sólido",
    "simbolo": "Am",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1944",
    "linha": 10,
    "coluna": 10
  },
  {
    "massaAtomica": "247",
    "numeroAtomico": "96",
    "raioAtomico": "",
    "pontoDeEbulicao": "3383",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "785CE3",
    "densidade": "13.51",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f7 6d1 7s2",
    "grupo": "actinoid",
    "raioIonico": "97 (+3)",
    "energiaDeIonizacao": "581",
    "pontoDeFusao": "1618",
    "nome": "Curium",
    "estadosDeOxidacao": "3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Cm",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1944",
    "linha": 10,
    "coluna": 11
  },
  {
    "massaAtomica": "247",
    "numeroAtomico": "97",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "8A4FE3",
    "densidade": "14.78",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f9 7s2",
    "grupo": "actinoid",
    "raioIonico": "96 (+3)",
    "energiaDeIonizacao": "601",
    "pontoDeFusao": "1323",
    "nome": "Berkelium",
    "estadosDeOxidacao": "3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Bk",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1949",
    "linha": 10,
    "coluna": 12
  },
  {
    "massaAtomica": "251",
    "numeroAtomico": "98",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "metálica",
    "corHexCpk": "A136D4",
    "densidade": "15.1",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f10 7s2",
    "grupo": "actinoid",
    "raioIonico": "95 (+3)",
    "energiaDeIonizacao": "608",
    "pontoDeFusao": "1173",
    "nome": "Californium",
    "estadosDeOxidacao": "2, 3, 4",
    "estadoPadrao": "sólido",
    "simbolo": "Cf",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1950",
    "linha": 10,
    "coluna": 13
  },
  {
    "massaAtomica": "252",
    "numeroAtomico": "99",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "B31FD4",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f11 7s2",
    "grupo": "actinoid",
    "raioIonico": "",
    "energiaDeIonizacao": "619",
    "pontoDeFusao": "1133",
    "nome": "Einsteinium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "sólido",
    "simbolo": "Es",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1952",
    "linha": 10,
    "coluna": 14
  },
  {
    "massaAtomica": "257",
    "numeroAtomico": "100",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "B31FBA",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f12 7s2",
    "grupo": "actinoid",
    "raioIonico": "",
    "energiaDeIonizacao": "627",
    "pontoDeFusao": "1800",
    "nome": "Fermium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "",
    "simbolo": "Fm",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1952",
    "linha": 10,
    "coluna": 15
  },
  {
    "massaAtomica": "258",
    "numeroAtomico": "101",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "B30DA6",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f13 7s2",
    "grupo": "actinoid",
    "raioIonico": "",
    "energiaDeIonizacao": "635",
    "pontoDeFusao": "1100",
    "nome": "Mendelevium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "",
    "simbolo": "Md",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1955",
    "linha": 10,
    "coluna": 16
  },
  {
    "massaAtomica": "259",
    "numeroAtomico": "102",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "BD0D87",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f14 7s2",
    "grupo": "actinoid",
    "raioIonico": "",
    "energiaDeIonizacao": "642",
    "pontoDeFusao": "1100",
    "nome": "Nobelium",
    "estadosDeOxidacao": "2, 3",
    "estadoPadrao": "",
    "simbolo": "No",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1957",
    "linha": 10,
    "coluna": 17
  },
  {
    "massaAtomica": "262",
    "numeroAtomico": "103",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "C70066",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "1.3",
    "configuracaoEletronica": "[Rn] 5f14 7s2 7p1",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "1900",
    "nome": "Lawrencium",
    "estadosDeOxidacao": "3",
    "estadoPadrao": "",
    "simbolo": "Lr",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1961",
    "linha": 10,
    "coluna": 18
  },
  {
    "massaAtomica": "267",
    "numeroAtomico": "104",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "CC0059",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d2 7s2",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Rutherfordium",
    "estadosDeOxidacao": "4",
    "estadoPadrao": "",
    "simbolo": "Rf",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1969",
    "linha": 7,
    "coluna": 4
  },
  {
    "massaAtomica": "268",
    "numeroAtomico": "105",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "D1004F",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d3 7s2",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Dubnium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Db",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1967",
    "linha": 7,
    "coluna": 5
  },
  {
    "massaAtomica": "271",
    "numeroAtomico": "106",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "D90045",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d4 7s2",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Seaborgium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Sg",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1974",
    "linha": 7,
    "coluna": 6
  },
  {
    "massaAtomica": "272",
    "numeroAtomico": "107",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "E00038",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d5 7s2",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Bohrium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Bh",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1976",
    "linha": 7,
    "coluna": 7
  },
  {
    "massaAtomica": "270",
    "numeroAtomico": "108",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "E6002E",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d6 7s2",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Hassium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Hs",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1984",
    "linha": 7,
    "coluna": 8
  },
  {
    "massaAtomica": "276",
    "numeroAtomico": "109",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "EB0026",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d7 7s2",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Meitnerium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Mt",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1982",
    "linha": 7,
    "coluna": 9
  },
  {
    "massaAtomica": "281",
    "numeroAtomico": "110",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d9 7s1",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Darmstadtium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Ds",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1994",
    "linha": 7,
    "coluna": 10
  },
  {
    "massaAtomica": "280",
    "numeroAtomico": "111",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s1",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Roentgenium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Rg",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1994",
    "linha": 7,
    "coluna": 11
  },
  {
    "massaAtomica": "285",
    "numeroAtomico": "112",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s2",
    "grupo": "metal de transição",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Copernicium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Cn",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1996",
    "linha": 7,
    "coluna": 12
  },
  {
    "massaAtomica": "284",
    "numeroAtomico": "113",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s2 7p1",
    "grupo": "post-transition metal",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Nihonium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Nh",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "2003",
    "linha": 7,
    "coluna": 13
  },
  {
    "massaAtomica": "289",
    "numeroAtomico": "114",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s2 7p2",
    "grupo": "post-transition metal",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Flerovium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Fl",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "1998",
    "linha": 7,
    "coluna": 14
  },
  {
    "massaAtomica": "288",
    "numeroAtomico": "115",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s2 7p3",
    "grupo": "post-transition metal",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Moscovium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Mc",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "2003",
    "linha": 7,
    "coluna": 15
  },
  {
    "massaAtomica": "293",
    "numeroAtomico": "116",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s2 7p4",
    "grupo": "post-transition metal",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Livermorium",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Lv",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "2000",
    "linha": 7,
    "coluna": 16
  },
  {
    "massaAtomica": "294",
    "numeroAtomico": "117",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s2 7p5",
    "grupo": "post-transition metal",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Tennessine",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Ts",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "2010",
    "linha": 7,
    "coluna": 17
  },
  {
    "massaAtomica": "294",
    "numeroAtomico": "118",
    "raioAtomico": "",
    "pontoDeEbulicao": "",
    "tipoDeLigacao": "",
    "corHexCpk": "",
    "densidade": "",
    "afinidadeEletronica": "",
    "eletronegatividade": "",
    "configuracaoEletronica": "[Rn] 5f14 6d10 7s2 7p6",
    "grupo": "gás nobre",
    "raioIonico": "",
    "energiaDeIonizacao": "",
    "pontoDeFusao": "",
    "nome": "Oganesson",
    "estadosDeOxidacao": "",
    "estadoPadrao": "",
    "simbolo": "Og",
    "raioDeVanDerWaals": "",
    "anoDeDescoberta": "2002",
    "linha": 7,
    "coluna": 18
  }
]

colecaoElementos.forEach(e => {
  if (!e.corGrupo) {
    if (e.grupo === "metal alcalino") e.corGrupo = '#FF5733';
    else if (e.grupo === "metal alcalino-terroso") e.corGrupo = '#00C853'; // verde escuro vibrante
    else if (e.grupo === 'lantanídeo') e.corGrupo = '#FFD700';
    else if (e.grupo === 'actinoid') e.corGrupo = '#FF33A8';
    else if (e.grupo === 'metal de transição') e.corGrupo = '#3380FF';
    else if (e.grupo === 'metal') e.corGrupo = '#AAAAAA';
    else if (e.grupo === 'metalóide') e.corGrupo = '#00FFD0';
    else if (e.grupo === "não metal") e.corGrupo = '#00FF00';
    else if (e.grupo === 'halogênio') e.corGrupo = '#FF00FF';
    else if (e.grupo === 'gás nobre') e.corGrupo = '#FFD600'; // amarelo forte
    else if (e.grupo === 'post-transition metal') e.corGrupo = '#FF9800';
    else e.corGrupo = '#CCCCCC'; // cor padrão para grupos desconhecidos
  }
});
